name: ci

on:
  push:
    branches:
      - 'dev'

jobs:
  create-environment:
    runs-on: ubuntu-latest
    outputs:
      new_id: ${{ steps.clone-template.outputs.new_id }}
      env_unique: ${{ steps.clone-template.outputs.env_unique }}
    container:
        image: bunnyshell/cli:v0.6.0
    steps:
        - name: clone-template
          env: 
            BUNNYSHELL_TOKEN: ${{ secrets.BUNNYSHELL_TOKEN }}
          id: clone-template
          run: |
            bunnyshell-cli version
            bunnyshell-cli environments clone --id p2xKjb7EYM --name "demobooks-${{ github.run_number }}" 
