name: ci

on:
  push:
    branches:
      - 'dev'

jobs:
  create-environment:
    runs-on: ubuntu-latest
    outputs:
      new_id: ${{ steps.clone-template.outputs.new_id }}
      env_unique: ${{ steps.clone-template.outputs.env_unique }}
    container:
        image: bunnyshell/cli:v0.6.0
    steps:
        - name: clone-template
          id: clone-template
          run: |
            bunnyshell-cli environments clone --id p2xKjb7EYM --token ${{ secrets.BUNNYSHELL_TOKEN }} --name "demobooks-${{ github.run_number }}" -o json > bunnyresult
            new_id=$( cat bunnyresult | jq -r '.id' )
            env_unique=$( cat bunnyresult | jq -r '.namespace' )
            echo "::set-output name=new_id::$new_id"
            echo "::set-output name=env_unique::$env_unique"
  create-image:
    runs-on: ubuntu-latest
    needs: [create-environment]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: backend/
          target: prod
          push: true
          tags: crblanaru/backend:latest,crblanaru/backend:v0.0.${{ github.run_number }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: frontend/
          target: prod
          build-args: REACT_APP_BASE_API="backend-${{needs.create-environment.outputs.env_unique}}.bunnyenv.com"
          push: true
          tags: crblanaru/frontend:latest,crblanaru/frontend:v0.0.${{ github.run_number }}
  initialize-environment:
    runs-on: ubuntu-latest
    needs: [create-image, create-environment]
    container:
        image: bunnyshell/cli:v0.6.0
    steps:
        # need one more step here where I alter the image name for the helm chart by setting an environment variable
        # using sleep to give me time to perform this step manually
        - name: set-env-variable
          run: |
            var_id=$( bunnyshell-cli variables list --environment ${{needs.create-environment.outputs.new_id}} --token ${{ secrets.BUNNYSHELL_TOKEN }} -o json | jq -r '._embedded.item[0].id' )
            bunnyshell-cli variables edit --id $var_id --token ${{ secrets.BUNNYSHELL_TOKEN }} --value "v0.0.${{ github.run_number }}" -o json
        - name: deploy-environment
          run: |
            event_id=$( bunnyshell-cli environments deploy --id ${{needs.create-environment.outputs.new_id}} --token ${{ secrets.BUNNYSHELL_TOKEN }} -o json |  jq -r '.id' )
            bunnyshell-cli events show --id $event_id --monitor --token ${{ secrets.BUNNYSHELL_TOKEN }} -o json
  run-tests:
    runs-on: ubuntu-latest
    needs: [create-environment, initialize-environment]
    container:
        image: bunnyshell/cli:v0.6.0
    steps:
        - name: simple-tests
          run: |
            sleep 10
            status_code=$(curl --write-out %{http_code} --silent --output /dev/null "https://backend-${{needs.create-environment.outputs.env_unique}}.bunnyenv.com")
            if [[ "$status_code" -ne 200 ]] ; then
              echo "Site status changed to $status_code" | exit 1
            else
              exit 0
            fi
  clean-up:
    runs-on: ubuntu-latest
    needs: [create-environment, run-tests]
    container:
        image: bunnyshell/cli:v0.6.0
    steps:
        - name: delete-ephemeral
          run: |
            sleep 30
            bunnyshell-cli environments delete --id ${{needs.create-environment.outputs.new_id}} --token ${{ secrets.BUNNYSHELL_TOKEN }} -o json 
