name: ci

on:
  push:
    branches:
      - 'dev'

jobs:
  initialize-environment:
    runs-on: ubuntu-latest
    container:
        image: bunnyshell/cli:v0.6.0
    steps:
        # need one more step here where I alter the image name for the helm chart by setting an environment variable
        # using sleep to give me time to perform this step manually
        - name: set-env-variable
          run: |
            var_id=$( bunnyshell-cli variables list --environment 8MEpPrQEl6 --token ${{ secrets.BUNNYSHELL_TOKEN }} -o json | jq -r '._embedded.item[0].id' )
            bunnyshell-cli variables edit --id $var_id --token ${{ secrets.BUNNYSHELL_TOKEN }} --value "v0.0.${{ github.run_number }}" -o json

  
