name: ci

on:
  push:
    branches:
      - 'dev'

jobs:
  initialize-environment:
    runs-on: ubuntu-latest
    container:
        image: bunnyshell/cli:v0.6.1
    steps:
        # need one more step here where I alter the image name for the helm chart by setting an environment variable
        # using sleep to give me time to perform this step manually
        - name: set-env-variable
          run: |
            bunnyshell-cli variables list --environment 8MEpPrQEl6 --token ${{ secrets.BUNNYSHELL_TOKEN }} -o json 
